version: "3"
services:
  socialpost-api:
    image: ipsingh0788/socialpost-fastapi
    ports:
      - 80:8000
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PWD=${DB_PWD}
      - SIGN_KEY=${SIGN_KEY}
      - SIGN_ALGORITHM=${SIGN_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTE=${ACCESS_TOKEN_EXPIRE_MINUTE}
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - postgres-db:/var/lib/postgresql/data    # save DB data.

volumes:
  postgres-db:

